[build]
  base = "/"
  [build.environment]
    NODE_VERSION = "20"
[functions]
  external_node_modules = ["express", "mongodb"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/api/:splat"